// Language to flag emoji mapping
export const languageFlags = {
    // Major languages
    'English': '🇬🇧',
    'Spanish': '🇪🇸',
    'Español': '🇪🇸',
    'French': '🇫🇷',
    'Français': '🇫🇷',
    'German': '🇩🇪',
    'Deutsch': '🇩🇪',
    'Italian': '🇮🇹',
    'Italiano': '🇮🇹',
    'Portuguese': '🇵🇹',
    'Português': '🇵🇹',
    'Russian': '🇷🇺',
    'Русский': '🇷🇺',
    'Chinese': '🇨🇳',
    'Mandarin': '🇨🇳',
    '中文': '🇨🇳',
    'Japanese': '🇯🇵',
    '日本語': '🇯🇵',
    'Korean': '🇰🇷',
    '한국어': '🇰🇷',
    'Arabic': '🇸🇦',
    'العربية': '🇸🇦',
    'Hindi': '🇮🇳',
    'हिन्दी': '🇮🇳',
    'Bengali': '🇧🇩',
    'বাংলা': '🇧🇩',
    'Urdu': '🇵🇰',
    'اردو': '🇵🇰',
    'Turkish': '🇹🇷',
    'Türkçe': '🇹🇷',
    'Polish': '🇵🇱',
    'Polski': '🇵🇱',
    'Dutch': '🇳🇱',
    'Nederlands': '🇳🇱',
    'Swedish': '🇸🇪',
    'Svenska': '🇸🇪',
    'Danish': '🇩🇰',
    'Dansk': '🇩🇰',
    'Norwegian': '🇳🇴',
    'Norsk': '🇳🇴',
    'Finnish': '🇫🇮',
    'Suomi': '🇫🇮',
    'Greek': '🇬🇷',
    'Ελληνικά': '🇬🇷',
    'Czech': '🇨🇿',
    'Čeština': '🇨🇿',
    'Romanian': '🇷🇴',
    'Română': '🇷🇴',
    'Hungarian': '🇭🇺',
    'Magyar': '🇭🇺',
    'Thai': '🇹🇭',
    'ไทย': '🇹🇭',
    'Vietnamese': '🇻🇳',
    'Tiếng Việt': '🇻🇳',
    'Indonesian': '🇮🇩',
    'Bahasa Indonesia': '🇮🇩',
    'Malay': '🇲🇾',
    'Bahasa Melayu': '🇲🇾',
    'Tagalog': '🇵🇭',
    'Filipino': '🇵🇭',
    'Hebrew': '🇮🇱',
    'עברית': '🇮🇱',
    'Persian': '🇮🇷',
    'Farsi': '🇮🇷',
    'فارسی': '🇮🇷',
    'Swahili': '🇰🇪',
    'Kiswahili': '🇰🇪',
    'Amharic': '🇪🇹',
    'አማርኛ': '🇪🇹',
    'Zulu': '🇿🇦',
    'isiZulu': '🇿🇦',
    'Xhosa': '🇿🇦',
    'isiXhosa': '🇿🇦',
    'Afrikaans': '🇿🇦',
    'Catalan': '🇪🇸',
    'Català': '🇪🇸',
    'Basque': '🇪🇸',
    'Euskara': '🇪🇸',
    'Welsh': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'Cymraeg': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'Irish': '🇮🇪',
    'Gaeilge': '🇮🇪',
    'Scottish Gaelic': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'Gàidhlig': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'Icelandic': '🇮🇸',
    'Íslenska': '🇮🇸',
    'Yoruba': '🇳🇬',
    'Èdè Yorùbá': '🇳🇬',
    'Igbo': '🇳🇬',
    'Asụsụ Igbo': '🇳🇬',
    'Hausa': '🇳🇬',
    'Ukrainian': '🇺🇦',
    'Українська': '🇺🇦',
    'Serbian': '🇷🇸',
    'Српски': '🇷🇸',
    'Croatian': '🇭🇷',
    'Hrvatski': '🇭🇷',
    'Bosnian': '🇧🇦',
    'Bosanski': '🇧🇦',
    'Slovenian': '🇸🇮',
    'Slovenščina': '🇸🇮',
    'Slovak': '🇸🇰',
    'Slovenčina': '🇸🇰',
    'Bulgarian': '🇧🇬',
    'Български': '🇧🇬',
    'Albanian': '🇦🇱',
    'Shqip': '🇦🇱',
    'Lithuanian': '🇱🇹',
    'Lietuvių': '🇱🇹',
    'Latvian': '🇱🇻',
    'Latviešu': '🇱🇻',
    'Estonian': '🇪🇪',
    'Eesti': '🇪🇪',
    'Georgian': '🇬🇪',
    'ქართული': '🇬🇪',
    'Armenian': '🇦🇲',
    'Հայերեն': '🇦🇲',

    // Sign languages - use hand emoji
    'ASL': '🤟',
    'American Sign Language': '🤟',
    'BSL': '🤟',
    'British Sign Language': '🤟',
    'Auslan': '🤟',
    'Australian Sign Language': '🤟',
    'LSF': '🤟',
    'French Sign Language': '🤟',
    'DGS': '🤟',
    'German Sign Language': '🤟',
    'JSL': '🤟',
    'Japanese Sign Language': '🤟',
    'KSL': '🤟',
    'Korean Sign Language': '🤟',
    'CSL': '🤟',
    'Chinese Sign Language': '🤟',
    'ISL': '🤟',
    'Indian Sign Language': '🤟',
    'LSE': '🤟',
    'Spanish Sign Language': '🤟',
    'LIS': '🤟',
    'Italian Sign Language': '🤟',
    'International Sign': '🤟',
};

// Helper to get flag for a language
export const getLanguageFlag = (language) => {
    if (!language) return null;

    // Try exact match first
    if (languageFlags[language]) {
        return languageFlags[language];
    }

    // Try to extract base language (e.g., "Spanish (Español)" -> "Spanish")
    const baseLanguage = language.split('(')[0].trim();
    if (languageFlags[baseLanguage]) {
        return languageFlags[baseLanguage];
    }

    // Try to extract native name (e.g., "Spanish (Español)" -> "Español")
    const nativeMatch = language.match(/\(([^)]+)\)/);
    if (nativeMatch && languageFlags[nativeMatch[1]]) {
        return languageFlags[nativeMatch[1]];
    }

    return null;
};
